pop_size_dna_normal: SETME
pop_size_dna_onekg: SETME
pop_size_dna_tumor: SETME
pop_size_rna_normal: 0
pop_size_rna_tumor: 0
read_dna_normal: pe_count_normal_dna
read_dna_onekg: pe_count_normal_dna_onekg
read_dna_tumor: pe_count_tumor_dna
read_rna_normal: 0
read_rna_tumor: 0
sample_dna_normal: sample_count_normal_dna
sample_dna_onekg: sample_count_normal_dna_onekg
sample_dna_tumor: sample_count_tumor_dna
sample_rna_normal: 0
sample_rna_tumor: 0
upper_factor: 50
weight_dna: 1.0
weight_read: 0.5
weight_tumor: 0.5
